[project]
name = "usda-fdc-loader"
description = "A Python package to load and process USDA FoodData Central data."
authors = [{ name = "Jessy Williams", email = "jessy@jessywilliams.com" }]
maintainers = [{ name = "Jessy Williams", email = "jessy@jessywilliams.com" }]
license = { file = "license.txt" }
readme = "readme.md"
requires-python = ">=3.13"

scripts = { mnamer = "foodprep.__main__:main" }
urls = { repository = "https://github.com/jkwill87/usda-fdc-loader" }
dynamic = ["version", "dependencies"]

[tool.setuptools]
packages = ["foodprep"]
dynamic = { dependencies = { file = "requirements.txt" } }

[tool.setuptools.package-data]
"*" = ["license.txt", "readme.md"]

[dependency-groups]
dev = ["isort>=6.0.1", "ruff>=0.11.11", "setuptools_scm>=8.3"]

[build-system]
requires = ["setuptools >= 80.0.0", "setuptools_scm[toml] >= 8.3", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportGeneralTypeIssues = "information"
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
exclude = [".venv", ".vscode"]

[tool.isort]
profile = "black"
py_version = 313
line_length = 88
known_first_party = "foodprep"
combine_star = true
combine_straight_imports = true
overwrite_in_place = true

[tool.setuptools_scm]
local_scheme = "dirty-tag"
write_to = "foodprep/__version__.py"
write_to_template = '''# file generated by setuptools_scm
# don't change, don't track in version control

__version__ = "{version}"
'''
